# Módulos

In [1]:
from pathlib import Path
import os
import pandas as pd

In [2]:
p = Path(os.getcwd())
p = p.parents[2]
p1 = p / 'data' / 'processed' / 'precios.parquet'

df = pd.read_parquet(p1)

In [3]:
df.drop(columns=['id','name','price_overview','v_resnet','v_convnext'], inplace=True)

In [4]:
df.head(2)

,description_len,price_range,num_languages,release_year,total_games_by_publisher,total_games_by_developer,Action,Adventure,Casual,Early Access,...,PvP,Remote Play Together,Shared/Split Screen,Single-player,Steam Achievements,Steam Cloud,Steam Leaderboards,Steam Trading Cards,brillo,v_clip
0,292,"[0.01,4.99]",1,2023,2,2,1,1,1,0,...,0,0,0,1,0,0,0,0,75.0494,"[0.2145, 0.7089, 0.4787, -0.1489, -0.2111, -0...."
1,283,"[0.01,4.99]",1,2016,2,3,1,0,0,0,...,1,0,0,1,1,0,1,0,118.5272,"[0.0132, 0.5609, -0.1436, 0.267, 0.5333, -0.31..."

In [5]:
df['release_year'] = df['release_year'].apply(lambda x : int(x))

In [7]:
df.columns

Index(['description_len', 'price_range', 'num_languages', 'release_year',
       'total_games_by_publisher', 'total_games_by_developer', 'Action',
       'Adventure', 'Casual', 'Early Access', 'Indie', 'RPG', 'Simulation',
       'Strategy', 'Co-op', 'Custom Volume Controls', 'Family Sharing',
       'Full controller support', 'Multi-player', 'Online Co-op', 'Online PvP',
       'Partial Controller Support', 'Playable without Timed Input', 'PvP',
       'Remote Play Together', 'Shared/Split Screen', 'Single-player',
       'Steam Achievements', 'Steam Cloud', 'Steam Leaderboards',
       'Steam Trading Cards', 'brillo', 'v_clip'],
      dtype='str')

In [ ]:
columnas_categoricas = ['Action','Adventure', 'Casual', 'Early Access', 'Indie', 'RPG', 'Simulation',
       'Strategy', 'Co-op', 'Custom Volume Controls', 'Family Sharing',
       'Full controller support', 'Multi-player', 'Online Co-op', 'Online PvP',
       'Partial Controller Support', 'Playable without Timed Input', 'PvP',
       'Remote Play Together', 'Shared/Split Screen', 'Single-player',
       'Steam Achievements', 'Steam Cloud', 'Steam Leaderboards', 'Steam Trading Cards']

,description_len,price_range,num_languages,release_year,total_games_by_publisher,total_games_by_developer,Action,Adventure,Casual,Early Access,...,PvP,Remote Play Together,Shared/Split Screen,Single-player,Steam Achievements,Steam Cloud,Steam Leaderboards,Steam Trading Cards,brillo,v_clip
0,292,"[0.01,4.99]",1,2023,2,2,1,1,1,0,...,0,0,0,1,0,0,0,0,75.0494,"[0.2145, 0.7089, 0.4787, -0.1489, -0.2111, -0...."
1,283,"[0.01,4.99]",1,2016,2,3,1,0,0,0,...,1,0,0,1,1,0,1,0,118.5272,"[0.0132, 0.5609, -0.1436, 0.267, 0.5333, -0.31..."
2,193,"[15.00,19.99]",14,2022,6,6,1,1,0,0,...,0,0,0,1,1,1,0,0,41.5843,"[-0.3364, 0.3606, -0.0104, 0.4718, -0.2495, 0...."
3,191,"[0.01,4.99]",14,2023,1,1,0,0,1,0,...,0,0,0,1,0,0,0,0,132.4635,"[-0.6552, -0.0782, 0.0193, -0.0049, 0.526, -0...."
4,143,"[15.00,19.99]",10,2024,14,1,0,0,1,0,...,1,1,1,1,1,0,0,0,153.6035,"[-0.3078, -0.0958, -0.349, -0.0634, -0.1079, -..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19988,267,"[5.00,9.99]",1,2025,1,1,1,0,0,0,...,0,1,1,1,1,0,0,0,66.7159,"[-0.3534, 0.4668, 0.3154, -0.0452, -0.2369, -0..."
19989,275,"[5.00,9.99]",1,2020,1,1,0,0,0,0,...,0,0,0,1,0,0,0,0,121.2984,"[-0.0571, 0.6264, 0.4445, -0.1714, 0.373, -0.5..."
19990,218,"[5.00,9.99]",1,2025,199,1,0,0,0,0,...,1,0,0,1,0,0,0,0,31.8229,"[-0.0038, 0.4327, -0.5112, 0.2094, 0.2648, -0...."
19991,116,"[0.01,4.99]",29,2019,2,35,0,0,0,0,...,0,0,0,1,1,1,0,0,135.9634,"[-0.0341, 0.0099, -0.1648, -0.3019, -0.0532, -..."
19992,293,"[5.00,9.99]",12,2015,2,2,0,1,1,0,...,0,0,0,1,1,1,0,1,86.5079,"[-0.2646, 0.3971, 0.1444, 0.354, 0.0779, -0.31..."

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split( X, y, test_size=0.3, random_state=42, stratify=y )
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp )

# CatBoost

In [ ]:
df.columns

## DataFrame Reduced

Transformacion inicial

In [ ]:
import pandas as pd

# Target
y = df['price_range']
X = df.drop(columns=['price_range'])

# Columnas categóricas (las tuyas)
cat_cols = [
       'Adventure', 'Casual', 'Early Access', 'Indie', 'RPG', 'Simulation',
       'Strategy', 'Co-op', 'Custom Volume Controls', 'Family Sharing',
       'Full controller support', 'Multi-player', 'Online Co-op', 'Online PvP',
       'Partial Controller Support', 'Playable without Timed Input', 'PvP',
       'Remote Play Together', 'Shared/Split Screen', 'Single-player',
       'Steam Achievements', 'Steam Cloud', 'Steam Leaderboards',
       'Steam Trading Cards'
]

# Convertir categóricas a string (seguro)
X[cat_cols] = X[cat_cols].astype(str)

# Asegurar numéricas correctas
num_cols = [
    'num_languages', 'release_year',
       'total_games_by_publisher', 'total_games_by_developer', 'description_len'
]

X[num_cols] = X[num_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
X.dtypes

Split

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

Pesos

In [ ]:

class_counts = y_train.value_counts().sort_index()
total = len(y_train)

class_weights = {
    cls: total / (len(class_counts) * count)
    for cls, count in class_counts.items()
}

print("Class weights:", class_weights)

In [ ]:
import optuna
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, f1_score

def objective(trial):

    params = {
        "iterations": trial.suggest_int("iterations", 300, 800),
        "depth": trial.suggest_int("depth", 4, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-3, 10, log=True),
        "border_count": trial.suggest_int("border_count", 32, 255),
        
        "loss_function": "MultiClass",
        "eval_metric": "TotalF1",
        "random_state": 42,
        "verbose": 0,

        "class_weights": class_weights 
    }

    model = CatBoostClassifier(**params)

    model.fit(
        X_train,
        y_train,
        cat_features=cat_cols,
        eval_set=(X_val, y_val),
        early_stopping_rounds=50,
        verbose=False
    )

    preds = model.predict(X_val)

    score = f1_score(y_val, preds, average='weighted')

    return score

In [ ]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)

print("Best params:", study.best_params)
print("Best score:", study.best_value)

In [ ]:
import wandb
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

best_params = study.best_params

run = wandb.init(
    entity="pd1-c2526-team4",
    project="Precios", 
    name='Cat Complete (NoImg) Weighted',
    job_type='catboost'
)


print(best_params)


final_model = CatBoostClassifier(**best_params)
final_model.fit(
        X_train,
        y_train,
        cat_features=cat_cols,
        eval_set=(X_val, y_val),
        early_stopping_rounds=50,
        verbose=False
    )

y_pred = final_model.predict(X_val)

print("Classification Report:")
cal = classification_report(y_val, y_pred)
print(cal)

print("Confusion Matrix:")
conf_matrix = confusion_matrix(y_val, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

accuracy = accuracy_score(y_val, y_pred)
precision = precision_score(y_val, y_pred, average='weighted')
recall = recall_score(y_val, y_pred, average='weighted')
f1 = f1_score(y_val, y_pred, average='weighted')

print(f'Acurracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1-Score: {f1}')
print(f'Confusion-Matrix: {conf_matrix}')


run.log({
    'accuracy': accuracy,
    'precision': precision,
    'recall': recall,
    'f1-score': f1,
    'confusion-matrix': conf_matrix.tolist() 
    })

run.finish()

## DataFrame Completo

In [ ]:
p = Path(os.getcwd())
p = p.parents[2]
p1 = p / 'data' / 'processed' / 'simple_prices.parquet'

df = pd.read_parquet(p1)

In [ ]:
df.head(2)

In [ ]:
df.columns